# Generated by Django 5.0.6 on 2024-06-24 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_rename_account_transaction_user_account'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='user_account',
            new_name='account',
        ),
    ]
