# Generated by Django 5.0.6 on 2024-06-24 11:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0001_initial'),
        ('transactions', '0006_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moneytransaction',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='authors.registration'),
        ),
    ]
